version: "3.8"

services:
  app:
    image: ${DOCKERHUB_NAME}/clokey-docker-2025:${DOCKER_TAG}
    container_name: clokey-app
    pull_policy: always
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod

      # Database
      PROD_MYSQL_HOST: ${PROD_MYSQL_HOST}
      MYSQL_PORT: ${MYSQL_PORT}
      DB_NAME: ${DB_NAME}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}

      # Redis
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_PASSWORD: ${REDIS_PASSWORD}

      # Kakao OIDC
      KAKAO_CLIENT_ID: ${KAKAO_CLIENT_ID}
      KAKAO_CLIENT_SECRET: ${KAKAO_CLIENT_SECRET}

      # Apple OIDC
      APPLE_CLIENT_ID: ${APPLE_CLIENT_ID}
      APPLE_CLIENT_SECRET: ${APPLE_CLIENT_SECRET}

      # Firebase
      FIREBASE_CREDENTIALS_PATH: /run/secrets/firebase-sa.json

      # JWT
      JWT_ACCESS_TOKEN_SECRET: ${JWT_ACCESS_TOKEN_SECRET}
      JWT_REFRESH_TOKEN_SECRET: ${JWT_REFRESH_TOKEN_SECRET}
      JWT_ACCESS_TOKEN_EXPIRATION_TIME: ${JWT_ACCESS_TOKEN_EXPIRATION_TIME}
      JWT_REFRESH_TOKEN_EXPIRATION_TIME: ${JWT_REFRESH_TOKEN_EXPIRATION_TIME}
      JWT_ISSUER: ${JWT_ISSUER}

      # AWS S3
      PROD_AWS_ACCESS_KEY_ID: ${PROD_AWS_ACCESS_KEY_ID}
      PROD_AWS_SECRET_ACCESS_KEY: ${PROD_AWS_SECRET_ACCESS_KEY}
      AWS_REGION: ${AWS_REGION}
      PROD_S3_BUCKET: ${PROD_S3_BUCKET}
      PROD_S3_ENDPOINT: ${PROD_S3_ENDPOINT}

      # Swagger
      SWAGGER_USERNAME: ${SWAGGER_USERNAME}
      SWAGGER_PASSWORD: ${SWAGGER_PASSWORD}

      AI_SERVER_IP: ${AI_SERVER_IP}
      CLOTH_INFERENCE_PATH: ${CLOTH_INFERENCE_PATH}
      STYLE_INFERENCE_PATH: ${STYLE_INFERENCE_PATH}
      CLOTH_DETECT_PATH: ${CLOTH_DETECT_PATH}

      # MeilieSearch
      MEILISEARCH_ENDPOINT: ${MEILISEARCH_ENDPOINT}
      MEILISEARCH_KEY: ${MEILISEARCH_KEY}

    volumes:
      - /home/ubuntu/secrets/firebase-sa.json:/run/secrets/firebase-sa.json:ro

    networks:
      - app_network

networks:
  app_network:
    name: app_network
    driver: bridge
