bootJar {
    enabled = false
}

jar {
    enabled = true
}

repositories {
    maven {
        url = 'https://jitpack.io'
    }
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-data-redis'
    api 'io.github.openfeign:feign-httpclient:12.1'
    api 'org.springframework.cloud:spring-cloud-starter-openfeign:3.1.4'
}
